

server:
  port: 4400

name: jsk
description: hello world

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/jsk?useSSL=false
    username: root
    password: 385152
  application:
    name: privider-user


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true



